GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Get New Tesla"
}

###
DELETE http://localhost:3001/todo/delete/6413103b14944c7fe81c137d

###

PUT http://localhost:3001/todo/complete/64130fbf14944c7fe81c1378